import json, html, os
S=os.environ["S"]
d=json.load(open("backtest_full.json")); rows=d["rows"]; sm=d["summary"]
f=lambda v: f"${v:,.0f}"; fp=lambda v: f"${v:+,.0f}"
H=["<title>Model v5 backtest</title><style>body{font:15px/1.45 -apple-system,system-ui,sans-serif;max-width:960px;margin:0 auto;padding:16px;color:#1b1b1b;background:#fff;overflow-x:hidden}h1{font-size:22px;margin:0 0 6px}h2{font-size:17px;margin:26px 0 8px}.sub{color:#555;font-size:13.5px;margin-bottom:14px}.tw{overflow-x:auto;margin:0 -16px;padding:0 16px}table{border-collapse:collapse;width:100%;font-variant-numeric:tabular-nums;font-size:14px}th,td{padding:6px 8px;border-bottom:1px solid #e3e3e3;text-align:right;white-space:nowrap}th:first-child,td:first-child{text-align:left;white-space:normal}th{font-size:12px;color:#555;text-transform:uppercase;letter-spacing:.03em}.pos{color:#1b5e20}.neg{color:#b71c1c}.box{background:#f4f4f4;padding:12px 14px;border-radius:6px;font-size:14px;margin:14px 0}.kpi{display:grid;grid-template-columns:repeat(auto-fit,minmax(150px,1fr));gap:10px;margin:14px 0}.k{background:#f4f4f4;padding:10px 12px;border-radius:6px}.k b{display:block;font-size:20px}.k span{font-size:12px;color:#555}@media(prefers-color-scheme:dark){body{background:#121212;color:#eee}.box,.k{background:#1f1f1f}.k span,.sub,th{color:#aaa}th,td{border-color:#333}}</style>",
"<h1>Model v5 backtest: the live betting rules</h1><div class='sub'>Races from 6 May to 1 Oct 2026 that the model never trained on: 1,355 races, 172 meetings. Bets: 20c+ over our price (stage 2 v4), our price $2 to $15, every no-bet rule applied, staked Kelly x75 on a chance halfway between ours and the market's, capped at 4 units, $100 a unit. Settled at the opening price and at Betfair SP less 8% commission.</div>"]
ov={r["label"]:r for r in rows if r["section"]=="Overall"}; L=ov["Live rules, Kelly on the 50/50 blend (final plan)"]
H.append(f"<div class='kpi'><div class='k'><b>{L['bets']:,}</b><span>bets, {sm['bets_per_meeting']:.1f} a meeting</span></div><div class='k'><b>{f(L['invested'])}</b><span>invested</span></div><div class='k'><b>{f(L['ret_open'])}</b><span>returned at the open</span></div><div class='k'><b class='pos'>{L['roi_open']:+.1f}%</b><span>ROI at the open</span></div><div class='k'><b class='{'pos' if L['roi_bsp']>=0 else 'neg'}'>{L['roi_bsp']:+.1f}%</b><span>ROI at BSP</span></div><div class='k'><b>{L['strike']:.1f}%</b><span>strike rate, avg price ${L['avg']:.2f}</span></div><div class='k'><b>{sm['longest_losing_run']}</b><span>longest losing run</span></div><div class='k'><b>{f(sm['max_drawdown_open'])}</b><span>worst drawdown at the open</span></div></div>")
H.append("<div class='box'><b>Read this first.</b> The opening prices in the history were filled in after the races from Form King's records, and on the live-pulled races they have been softer than what was actually on offer. The tables below carry no deductions for late scratchings; the orange line in the chart applies the live book's average (17.8c in the dollar per race), which takes the open figure to about +35%. The BSP column is the honest floor: it is the price everyone can get, and the model breaks even there. The profit lives between the two, and only a live book at prices actually taken proves how much of it is real.</div>")
def table(sec):
    rs=[r for r in rows if r["section"]==sec]
    if not rs: return
    H.append(f"<h2>{html.escape(sec)}</h2><div class='tw'><table><tr><th>{'' if sec=='Overall' else sec}</th><th>Bets</th><th>Wins</th><th>Strike</th><th>Avg price</th><th>Invested</th><th>Returned (open)</th><th>Profit (open)</th><th>ROI open</th><th>Profit (BSP)</th><th>ROI BSP</th></tr>")
    for r in rs:
        po=r["ret_open"]-r["invested"]; pb=r["ret_bsp"]-r["invested"]
        H.append(f"<tr><td>{html.escape(r['label'])}</td><td>{r['bets']:,}</td><td>{r['wins']}</td><td>{r['strike']:.1f}%</td><td>${r['avg']:.2f}</td><td>{f(r['invested'])}</td><td>{f(r['ret_open'])}</td><td class='{'pos' if po>=0 else 'neg'}'>{fp(po)}</td><td class='{'pos' if po>=0 else 'neg'}'>{r['roi_open']:+.1f}%</td><td class='{'pos' if pb>=0 else 'neg'}'>{fp(pb)}</td><td class='{'pos' if pb>=0 else 'neg'}'>{r['roi_bsp']:+.1f}%</td></tr>")
    H.append("</table></div>")
for sec in ("Overall","By month","By our price","By opening price","By overlay","By type","By going"): table(sec)
H.append("<h2>What it says</h2><div class='box'>Every month and every price band is well in front at the open and about level at BSP: the model's prices are as good as the closing market, and the edge is the gap between the opening market and where the price finishes. 77% of these bets shortened between the open and BSP, median move 28%. A 17% strike rate at an average of $12 means runs of 20 to 25 losers are normal. The second-up early-only bets are the best group per bet, which is why they came back in. The 20c-to-30c overlays earn least, and the staking plan puts the money on the shorter-priced, bigger overlays.</div>")
open(f"{S}/pages/backtest-v5.html","w").write("\n".join(H)); print("page ok")
